
services:
  db:
    image: postgres:16
    container_name: transcendence-db-postgres
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpasswd
      - POSTGRES_DB=transcendence
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - PORT=8080
      - FRONTEND_ORIGIN=http://localhost:3000
      - DATABASE_URL=postgresql://dbuser:dbpasswd@db:5432/transcendence?schema=public
    ports:
      - "8080:8080"
